In [2]:
# 필수 라이브러리
import pandas as pd

In [3]:
# 전체 데이터셋 읽어들이기
raw_df = pd.read_csv('./data/continuous_factory_process.csv', index_col="time_stamp")

raw_df_modify = raw_df.drop(raw_df.filter(regex='Setpoint').columns,axis=1)
#1번 모두 처리함(5~14까지의 컬럼 제거 즉 10개.)
raw_df_modify.describe()

,AmbientConditions.AmbientHumidity.U.Actual,AmbientConditions.AmbientTemperature.U.Actual,Machine1.RawMaterial.Property1,Machine1.RawMaterial.Property2,Machine1.RawMaterial.Property3,Machine1.RawMaterial.Property4,Machine1.RawMaterialFeederParameter.U.Actual,Machine1.Zone1Temperature.C.Actual,Machine1.Zone2Temperature.C.Actual,Machine1.MotorAmperage.U.Actual,...,Stage2.Output.Measurement5.U.Actual,Stage2.Output.Measurement6.U.Actual,Stage2.Output.Measurement7.U.Actual,Stage2.Output.Measurement8.U.Actual,Stage2.Output.Measurement9.U.Actual,Stage2.Output.Measurement10.U.Actual,Stage2.Output.Measurement11.U.Actual,Stage2.Output.Measurement12.U.Actual,Stage2.Output.Measurement13.U.Actual,Stage2.Output.Measurement14.U.Actual
count,11270.000000,11270.000000,11270.000000,11270.000000,11270.000000,11270.000000,11270.000000,11270.000000,11270.000000,11270.000000,...,1.127000e+04,1.127000e+04,1.127000e+04,1.127000e+04,11270.000000,1.127000e+04,1.127000e+04,1.127000e+04,1.127000e+04,11270.000000
mean,15.331195,23.842631,11.851032,205.670098,951.735828,248.870364,1242.634518,72.013212,72.011600,70.347306,...,2.743390e+00,5.324545e-01,2.912198e+00,1.835855e+01,11.620438,7.530888e+00,5.413007e+00,1.971135e+00,3.534162e+00,7.510250
std,1.188035,0.373258,0.509846,11.605754,126.701765,3.298604,96.812969,0.063138,0.405882,5.531330,...,3.897225e-01,2.069538e-01,5.175030e-01,5.020569e+00,7.618834,1.655847e+00,1.189045e+00,4.172279e-01,4.776323e-01,2.085541
min,13.840000,23.020000,11.540000,200.000000,601.110000,247.000000,231.300000,71.900000,71.300000,44.400000,...,-3.511350e-95,-3.698600e-105,-1.320100e-109,-3.026500e-104,-0.003719,-5.220420e-95,-2.703210e-95,-6.200020e-96,-1.822810e-95,-3.437021
25%,14.040000,23.530000,11.540000,200.000000,963.000000,247.000000,1257.220000,72.000000,71.600000,69.020000,...,2.660000e+00,4.300000e-01,2.960000e+00,1.941000e+01,0.000000,7.840000e+00,5.560000e+00,2.030000e+00,3.450000e+00,7.720000
50%,15.120000,23.930000,11.540000,200.000000,963.000000,247.000000,1264.530000,72.000000,72.000000,71.980000,...,2.730000e+00,5.500000e-01,2.980000e+00,1.969000e+01,16.570000,7.900000e+00,5.630000e+00,2.060000e+00,3.510000e+00,7.870000
75%,16.630000,24.160000,12.220000,201.000000,1027.430000,251.000000,1273.752500,72.000000,72.400000,72.920000,...,2.930000e+00,6.500000e-01,3.000000e+00,1.998000e+01,16.660000,7.950000e+00,5.800000e+00,2.090000e+00,3.760000e+00,8.080000
max,17.240000,24.430000,12.900000,236.000000,1048.060000,257.000000,1331.820000,72.500000,72.700000,88.530000,...,8.110000e+00,3.310000e+00,7.450000e+00,2.475599e+01,18.360000,8.590000e+00,6.320000e+00,5.200000e+00,8.000000e+00,14.260000

In [4]:
raw_df_machine0 = raw_df_modify.filter(regex='AmbientConditions') 
raw_df_machine1 = raw_df_modify.filter(regex='Machine1') #machine1인 데이터값만 가져옴
raw_df_machine2 = raw_df_modify.filter(regex='Machine2') 
raw_df_machine3 = raw_df_modify.filter(regex='Machine3') 
raw_df_machine4 = raw_df_modify.filter(regex='Machine4') 
raw_df_machine5 = raw_df_modify.filter(regex='Machine5') 
raw_df_stage1 = raw_df_modify.filter(regex='Stage1') 
raw_df_stage2 = raw_df_modify.filter(regex='Stage2') 
raw_df_firststage = raw_df_modify.filter(regex='FirstStage')

In [5]:
# machine1 전처리

,Machine4.Temperature1.C.Actual,Machine4.Temperature2.C.Actual,Machine4.Pressure.C.Actual,Machine4.Temperature3.C.Actual,Machine4.Temperature4.C.Actual,Machine4.Temperature5.C.Actual,Machine4.ExitTemperature.U.Actual
time_stamp,,,,,,,
2019-03-06 10:52:33,298.0,284.0,21.0,268.0,21.0,260.0,35.0
2019-03-06 10:52:38,317.0,299.0,22.0,280.0,22.0,275.0,35.0
2019-03-06 10:52:40,321.0,302.0,25.0,284.0,25.0,283.0,35.0
2019-03-06 10:52:42,327.0,308.0,25.0,288.0,25.0,288.0,36.0
2019-03-06 10:52:43,330.0,311.0,24.0,291.0,24.0,290.0,37.0
...,...,...,...,...,...,...,...
2019-03-06 14:47:13,360.0,359.0,18.0,326.0,18.0,311.0,196.0
2019-03-06 14:47:16,361.0,359.0,18.0,326.0,18.0,311.0,195.0
2019-03-06 14:47:17,361.0,359.0,19.0,326.0,19.0,311.0,195.0
2019-03-06 14:47:18,361.0,359.0,17.0,326.0,17.0,311.0,195.0
2019-03-06 14:47:20,361.0,359.0,19.0,325.0,19.0,311.0,196.0

In [62]:
raw_df_machine1['Machine1.RawMaterial.Property3']= raw_df_machine1['Machine1.RawMaterial.Property3']/2

<ipython-input-62-ae66639f2f91>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_df_machine1['Machine1.RawMaterial.Property3']= raw_df_machine1['Machine1.RawMaterial.Property3']/2

In [89]:
raw_df_machine1

,Machine1.RawMaterial.Property1,Machine1.RawMaterial.Property2,Machine1.RawMaterial.Property3,Machine1.RawMaterial.Property4,Machine1.RawMaterialFeederParameter.U.Actual,Machine1.Zone1Temperature.C.Actual,Machine1.Zone2Temperature.C.Actual,Machine1.MotorAmperage.U.Actual,Machine1.MotorRPM.C.Actual,Machine1.MaterialPressure.U.Actual,Machine1.MaterialTemperature.U.Actual,Machine1.ExitZoneTemperature.C.Actual
time_stamp,,,,,,,,,,,,
2019-03-06 10:52:33,11.54,200,240.750,247,1241.26,72.0,72.3,48.03,10.48,436.76,76.3,75.1
2019-03-06 10:52:38,11.54,200,240.750,247,1262.73,72.1,72.4,48.70,10.48,435.23,76.4,75.1
2019-03-06 10:52:40,11.54,200,240.750,247,1296.13,72.1,72.4,49.78,10.48,439.68,76.4,75.0
2019-03-06 10:52:42,11.54,200,240.750,247,1202.16,72.1,72.4,49.64,10.52,431.83,76.5,75.0
2019-03-06 10:52:43,11.54,200,240.750,247,1202.57,72.1,72.4,49.37,10.48,430.50,76.5,75.1
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-06 14:47:13,12.22,201,262.015,252,1258.05,72.0,71.8,73.05,12.14,429.02,83.7,80.0
2019-03-06 14:47:16,12.22,201,262.015,252,1263.76,72.0,71.8,73.46,12.21,424.53,83.7,80.0
2019-03-06 14:47:17,12.22,201,262.015,252,1255.42,72.0,71.8,73.32,12.17,426.73,83.7,80.0
2019-03-06 14:47:18,12.22,201,262.015,252,1257.52,72.0,71.8,73.59,12.14,429.77,83.7,80.0
2019-03-06 14:47:20,12.22,201,262.015,252,1257.40,72.0,71.9,73.86,12.17,435.96,83.7,80.0

In [88]:
y=raw_df_stage1

In [87]:
X = pd.concat([raw_df_machine0,raw_df_machine1,raw_df_machine2,raw_df_machine3,raw_df_firststage],axis=1)

In [82]:
#stage1 모델생성
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [83]:
linear_model = LinearRegression()

In [84]:
#stage1 모델평가
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=915)

In [90]:
#stage1 모델학습
linear_model.fit(X_train,y_train)

LinearRegression()

In [91]:
linear_model.predict(X_test).shape

(2254, 15)

In [92]:
#stage1 제출
submission = pd.read_csv('data/submission_data.csv') #제출파일 불러오기

In [93]:
submission_modify = submission.drop(raw_df.filter(regex='Setpoint').columns,axis=1) #제출파일에서도 컬럼제거

In [94]:
X_stage1_test = submission_modify.iloc[:,1:42] #제출파일의 문제데이터 가져오기

In [95]:
X_test.shape

(2254, 41)

In [96]:
best_pre=linear_model.predict(X_test) #제출파일의 정답데이터 예측

In [106]:
best_pre.shape #stage1의 제출할 정답데이터

(2254, 15)

In [107]:
submission_modify.shape

(2818, 86)

In [109]:
submission_modify.iloc[:,42:57]
submission_modify.iloc[:,42:57] =  best_pre #submission1의 예측값만 저장
submission1 = submission_modify.iloc[:,42:57]

,Stage1.Output.Measurement0.U.Actual,Stage1.Output.Measurement1.U.Actual,Stage1.Output.Measurement2.U.Actual,Stage1.Output.Measurement3.U.Actual,Stage1.Output.Measurement4.U.Actual,Stage1.Output.Measurement5.U.Actual,Stage1.Output.Measurement6.U.Actual,Stage1.Output.Measurement7.U.Actual,Stage1.Output.Measurement8.U.Actual,Stage1.Output.Measurement9.U.Actual,Stage1.Output.Measurement10.U.Actual,Stage1.Output.Measurement11.U.Actual,Stage1.Output.Measurement12.U.Actual,Stage1.Output.Measurement13.U.Actual,Stage1.Output.Measurement14.U.Actual
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#STAGE2

In [99]:
raw_df_machine4 = raw_df_modify.filter(regex='Machine4') #machine1인 데이터값만 가져옴
raw_df_machine5 = raw_df_modify.filter(regex='Machine5') #machine1인 데이터값만 가져옴
raw_df_stage1 = raw_df_modify.filter(regex='Stage1') #machine1인 데이터값만 가져옴
raw_df_stage2 = raw_df_modify.filter(regex='Stage2') #machine1인 데이터값만 가져옴

In [24]:
raw_df_machine4

,Machine4.Temperature1.C.Actual,Machine4.Temperature2.C.Actual,Machine4.Pressure.C.Actual,Machine4.Temperature3.C.Actual,Machine4.Temperature4.C.Actual,Machine4.Temperature5.C.Actual,Machine4.ExitTemperature.U.Actual
time_stamp,,,,,,,
2019-03-06 10:52:33,298.0,284.0,21.0,268.0,21.0,260.0,35.0
2019-03-06 10:52:38,317.0,299.0,22.0,280.0,22.0,275.0,35.0
2019-03-06 10:52:40,321.0,302.0,25.0,284.0,25.0,283.0,35.0
2019-03-06 10:52:42,327.0,308.0,25.0,288.0,25.0,288.0,36.0
2019-03-06 10:52:43,330.0,311.0,24.0,291.0,24.0,290.0,37.0
...,...,...,...,...,...,...,...
2019-03-06 14:47:13,360.0,359.0,18.0,326.0,18.0,311.0,196.0
2019-03-06 14:47:16,361.0,359.0,18.0,326.0,18.0,311.0,195.0
2019-03-06 14:47:17,361.0,359.0,19.0,326.0,19.0,311.0,195.0
2019-03-06 14:47:18,361.0,359.0,17.0,326.0,17.0,311.0,195.0
2019-03-06 14:47:20,361.0,359.0,19.0,325.0,19.0,311.0,196.0

In [25]:
raw_df_machine5

,Machine5.Temperature1.C.Actual,Machine5.Temperature2.C.Actual,Machine5.Temperature3.C.Actual,Machine5.Temperature4.C.Actual,Machine5.Temperature5.C.Actual,Machine5.Temperature6.C.Actual,Machine5.ExitTemperature.U.Actual
time_stamp,,,,,,,
2019-03-06 10:52:33,309.8,289.9,263.9,238.6,245.0,66.1,50.0
2019-03-06 10:52:38,309.8,289.8,263.9,238.6,245.0,66.1,49.1
2019-03-06 10:52:40,309.7,289.8,263.9,238.6,245.0,66.0,49.4
2019-03-06 10:52:42,309.5,289.8,263.9,238.6,245.0,66.0,49.4
2019-03-06 10:52:43,309.4,289.8,263.9,238.6,245.0,66.0,48.5
...,...,...,...,...,...,...,...
2019-03-06 14:47:13,310.0,290.0,270.0,244.7,245.0,63.7,155.2
2019-03-06 14:47:16,310.0,289.9,270.0,244.7,245.0,63.7,155.4
2019-03-06 14:47:17,310.0,289.9,270.0,244.7,245.0,63.7,155.1
2019-03-06 14:47:18,310.0,289.9,270.0,244.7,245.0,63.7,155.1
2019-03-06 14:47:20,310.0,289.9,270.0,244.7,245.0,63.7,155.2

In [26]:
#stage2의 입력데이터 합치기
X_stage2 = pd.concat([raw_df_machine4,raw_df_machine5],axis=1)

In [100]:
#stage2의 정답데이터
y_stage2 = raw_df_stage2
y_stage2

,Stage2.Output.Measurement0.U.Actual,Stage2.Output.Measurement1.U.Actual,Stage2.Output.Measurement2.U.Actual,Stage2.Output.Measurement3.U.Actual,Stage2.Output.Measurement4.U.Actual,Stage2.Output.Measurement5.U.Actual,Stage2.Output.Measurement6.U.Actual,Stage2.Output.Measurement7.U.Actual,Stage2.Output.Measurement8.U.Actual,Stage2.Output.Measurement9.U.Actual,Stage2.Output.Measurement10.U.Actual,Stage2.Output.Measurement11.U.Actual,Stage2.Output.Measurement12.U.Actual,Stage2.Output.Measurement13.U.Actual,Stage2.Output.Measurement14.U.Actual
time_stamp,,,,,,,,,,,,,,,
2019-03-06 10:52:33,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
2019-03-06 10:52:38,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
2019-03-06 10:52:40,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
2019-03-06 10:52:42,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
2019-03-06 10:52:43,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-03-06 14:47:13,13.00,0.00,11.05,19.35,0.0,3.13,0.31,2.98,19.35,0.0,7.88,5.53,2.06,3.86,7.60
2019-03-06 14:47:16,12.91,6.40,10.95,19.07,0.0,3.09,0.23,2.97,20.08,0.0,7.87,5.53,2.07,3.80,7.56
2019-03-06 14:47:17,12.90,6.47,10.89,19.11,0.0,2.94,0.21,2.97,19.57,0.0,7.85,5.48,2.01,3.79,7.76
2019-03-06 14:47:18,13.08,6.44,10.86,19.42,0.0,3.03,0.27,2.96,19.18,0.0,7.93,5.54,2.06,3.83,7.66
2019-03-06 14:47:20,13.11,6.41,10.79,19.45,0.0,2.96,0.46,2.92,19.30,0.0,7.85,5.51,2.05,3.83,7.87

In [28]:
#제출할 데이터에서 문제+정답데이터만 출력
submission2 = submission_modify.iloc[:,57:] 
submission2

,Machine4.Temperature1.C.Actual,Machine4.Temperature2.C.Actual,Machine4.Pressure.C.Actual,Machine4.Temperature3.C.Actual,Machine4.Temperature4.C.Actual,Machine4.Temperature5.C.Actual,Machine4.ExitTemperature.U.Actual,Machine5.Temperature1.C.Actual,Machine5.Temperature2.C.Actual,Machine5.Temperature3.C.Actual,...,Stage2.Output.Measurement5.U.Actual,Stage2.Output.Measurement6.U.Actual,Stage2.Output.Measurement7.U.Actual,Stage2.Output.Measurement8.U.Actual,Stage2.Output.Measurement9.U.Actual,Stage2.Output.Measurement10.U.Actual,Stage2.Output.Measurement11.U.Actual,Stage2.Output.Measurement12.U.Actual,Stage2.Output.Measurement13.U.Actual,Stage2.Output.Measurement14.U.Actual
0,301.0,287.0,23.0,270.0,23.0,263.0,35.0,309.8,289.9,263.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,304.0,289.0,22.0,275.0,22.0,266.0,35.0,309.8,289.9,263.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,307.0,291.0,23.0,277.0,23.0,269.0,35.0,309.8,289.9,263.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,310.0,294.0,24.0,278.0,24.0,272.0,35.0,309.8,289.9,263.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,317.0,299.0,22.0,282.0,22.0,278.0,35.0,309.8,289.8,263.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2813,360.0,360.0,19.0,326.0,19.0,312.0,194.0,310.0,290.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2814,360.0,360.0,18.0,326.0,18.0,311.0,195.0,310.0,290.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2815,361.0,359.0,19.0,326.0,19.0,311.0,196.0,310.0,290.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2816,361.0,359.0,18.0,326.0,18.0,311.0,195.0,310.0,289.9,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2817,361.0,359.0,18.0,326.0,18.0,311.0,195.0,310.0,289.9,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
#stage2 모델생성
linear_model2 = LinearRegression()

In [30]:
#stage2 모델학습
linear_model2.fit(X_stage2,y_stage2) #모델학습

LinearRegression()

In [101]:
#제출할 데이터에서 문제만 출력
X_stage2_test=submission2.iloc[:,0:14]
X_stage2_test

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [102]:
best_pre2 = linear_model2.predict(X_stage2_test) #stage2 정답데이터
best_pre2

array([[-2.11407199e+00,  2.06874722e+00, -8.11561138e-01, ...,
         1.01446736e-02,  1.50692992e+00,  1.70310640e+00],
       [-2.82487060e+00,  1.30641065e+00, -1.28167914e+00, ...,
        -1.54607422e-01,  1.43112254e+00,  6.96494825e-01],
       [-2.78749260e+00,  1.13226299e+00, -1.20064367e+00, ...,
        -1.66095545e-01,  1.38862636e+00,  4.50033414e-01],
       ...,
       [ 1.24610358e+01,  6.21740571e+00,  1.09380624e+01, ...,
         2.06642226e+00,  3.91997417e+00,  7.34549525e+00],
       [ 1.27321741e+01,  6.31481813e+00,  1.09596397e+01, ...,
         2.06153528e+00,  3.88338581e+00,  7.55444105e+00],
       [ 1.27315447e+01,  6.31877409e+00,  1.09641573e+01, ...,
         2.06185142e+00,  3.88820525e+00,  7.55674309e+00]])

In [40]:
submission2.iloc[:,14:] = best_pre2
submission2=submission2.iloc[:,14:]

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [39]:
submission2

array([[-2.11407199e+00,  2.06874722e+00, -8.11561138e-01, ...,
         1.01446736e-02,  1.50692992e+00,  1.70310640e+00],
       [-2.82487060e+00,  1.30641065e+00, -1.28167914e+00, ...,
        -1.54607422e-01,  1.43112254e+00,  6.96494825e-01],
       [-2.78749260e+00,  1.13226299e+00, -1.20064367e+00, ...,
        -1.66095545e-01,  1.38862636e+00,  4.50033414e-01],
       ...,
       [ 1.24610358e+01,  6.21740571e+00,  1.09380624e+01, ...,
         2.06642226e+00,  3.91997417e+00,  7.34549525e+00],
       [ 1.27321741e+01,  6.31481813e+00,  1.09596397e+01, ...,
         2.06153528e+00,  3.88338581e+00,  7.55444105e+00],
       [ 1.27315447e+01,  6.31877409e+00,  1.09641573e+01, ...,
         2.06185142e+00,  3.88820525e+00,  7.55674309e+00]])

In [103]:
submission1 = submission1.to_numpy()

NameError: name 'submission1' is not defined

In [36]:
submission1 = submission1.astype(int)
submission1.dtype

NameError: name 'submission1' is not defined

In [37]:
submission2 = submission2.to_numpy()

In [425]:
submission2 = submission2.astype(int)

In [426]:
submission1.shape, submission2.shape

((2818, 15), (2818, 15))

In [427]:
import numpy as np
np.save('submission1.npy', submission1)

In [428]:
import numpy as np
np.save('submission2.npy', submission2)

In [429]:
submission2[0]

array([-2,  2,  0, -2, 24,  0,  0,  0, -5, -7,  0,  0,  0,  1,  1])

# 제출 및 채점

아래 코드를 수정하면 정상적인 채점을 수행할 수 없습니다.

In [430]:
import sys
sys.path.append('vendor')
from elice_challenge import check_score, upload

In [431]:
# 제출 파일 업로드
await upload()

이전에 업로드 된 파일 삭제중...
업로드가 완료되었습니다.

In [432]:
# 채점 수행
await check_score()

TypeError: %d format: a number is required, not str